### ISSUE TITLE
 Gatling User Group › Issue in build in Jenkins, with Gatling project - java.lang.NoClassDefFoundError: com/typesafe/zinc/Setup

### ISSUE THREAD

**Issue by prakhu** [gatling/gatling-maven#5]
Hi,

I am facing errors while building my Gatling project in Jenkins:
1. Plugin used in project with version 2.1.5

    <plugin>
				<groupId>io.gatling</groupId>
				<artifactId>gatling-maven-plugin</artifactId>
				<version>${gatling-plugin.version}</version>
				<executions>
					<execution>
						<phase>test</phase>
						<goals>
							<goal>execute</goal>
						</goals>
						<configuration>
							
							
							<dataFolder>src/test/resources/data</dataFolder>
							<resultsFolder>target/gatling/results</resultsFolder>
							<requestBodiesFolder>src/test/resources/request-bodies</requestBodiesFolder>
							<simulationsFolder>src/test/scala</simulationsFolder>
						</configuration>
					</execution>
				</executions>
			</plugin>

2. I am using Jenkins 1.1.0 plugin which supports Gatling 2.

3. Error getting in Jenkins:
      [INFO] --- gatling-maven-plugin:2.1.5:execute (default) @ flightsearch-api ---
java.lang.NoClassDefFoundError: com/typesafe/zinc/Setup
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
	at java.lang.Class.getMethod0(Class.java:3010)
	at java.lang.Class.getMethod(Class.java:1776)
	at io.gatling.mojo.MainWithArgsInFile.runMain(MainWithArgsInFile.java:43)
	at io.gatling.mojo.MainWithArgsInFile.main(MainWithArgsInFile.java:33)
Caused by: java.lang.ClassNotFoundException: com.typesafe.zinc.Setup
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

Please advice.

Thanks,
Prakhar Srivastava

**Comment by slandelle** [comment]
@prakhu Please stop spamming! I've answered on the mailing list. I'll reopen if this is indeed an issue and not a broken maven download.
